import { subDays } from "date-fns";
import { and, count, desc, eq, gte, isNull, lte } from "drizzle-orm";
import { db } from "@/db";
import { attendance, members, membershipPlans, memberships, users } from "@/db/schema";
export function localDateFor(timezone: string, date = new Date()) { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(date); const part = (type: string) => parts.find(item => item.type === type)?.value; return `${part("year")}-${part("month")}-${part("day")}`; }
export async function attendanceTotals(gymId: string, timezone: string, now = new Date(), trainerId?: string) { const today = localDateFor(timezone, now), week = localDateFor(timezone, subDays(now, 6)), month = `${today.slice(0, 7)}-01`; const filters = (extra: ReturnType<typeof gte> | ReturnType<typeof isNull>) => and(eq(attendance.gymId, gymId), extra, ...(trainerId ? [eq(members.trainerId, trainerId)] : [])); const total = async (from: string) => (await ((db.select({ value: count() }).from(attendance)).innerJoin(members, eq(attendance.memberId, members.id))).where(filters(gte(attendance.localDate, from))))[0]?.value ?? 0; const inside = (await ((db.select({ value: count() }).from(attendance)).innerJoin(members, eq(attendance.memberId, members.id))).where(filters(isNull(attendance.checkOutAt))))[0]?.value ?? 0; return { today: await total(today), week: await total(week), month: await total(month), inside }; }
export async function recentAttendance(gymId: string, limit = 12) { return await (((((db.select({ id: attendance.id, memberId: members.id, firstName: members.firstName, lastName: members.lastName, memberNumber: members.memberNumber, checkInAt: attendance.checkInAt, checkOutAt: attendance.checkOutAt, method: attendance.method, overrideUsed: attendance.overrideUsed, staffName: users.name }).from(attendance)).innerJoin(members, eq(attendance.memberId, members.id))).innerJoin(users, eq(attendance.staffUserId, users.id))).where(eq(attendance.gymId, gymId))).orderBy(desc(attendance.checkInAt))).limit(limit); }
export async function memberAttendance(gymId: string, memberId: string, limit = 50) { return await (((db.select().from(attendance)).where(and(eq(attendance.gymId, gymId), eq(attendance.memberId, memberId)))).orderBy(desc(attendance.checkInAt))).limit(limit); }
export async function attendanceCandidate(gymId: string, memberId: string, now = new Date()) {
    const member = (await (db.select().from(members)).where(and(eq(members.gymId, gymId), eq(members.id, memberId), isNull(members.archivedAt))))[0];
    if (!member)
        return null;
    const membership = (await (((db.select({ id: memberships.id, status: memberships.status, startsAt: memberships.startsAt, endsAt: memberships.endsAt, plan: membershipPlans.name }).from(memberships)).innerJoin(membershipPlans, eq(memberships.planId, membershipPlans.id))).where(and(eq(memberships.gymId, gymId), eq(memberships.memberId, memberId), lte(memberships.startsAt, now), gte(memberships.endsAt, now)))).orderBy(desc(memberships.endsAt)))[0] ?? null;
    const open = (await (db.select().from(attendance)).where(and(eq(attendance.gymId, gymId), eq(attendance.memberId, memberId), isNull(attendance.checkOutAt))))[0] ?? null;
    const last = (await ((db.select({ checkInAt: attendance.checkInAt, checkOutAt: attendance.checkOutAt }).from(attendance)).where(and(eq(attendance.gymId, gymId), eq(attendance.memberId, memberId)))).orderBy(desc(attendance.checkInAt)))[0] ?? null;
    const valid = member.status === "active" && membership?.status === "active";
    const reason = member.status !== "active" ? `Member account is ${member.status}.` : !membership ? "No membership is valid today." : membership.status !== "active" ? `Membership is ${membership.status}.` : null;
    return { member, membership, open, last, valid, reason };
}
