import Link from "next/link";
import { and, desc, eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { CalendarCheck, CircleDollarSign, Clock3, Dumbbell, Mail, MapPin, NotebookPen, Pencil, Phone, RefreshCw, ShieldPlus, Snowflake, UserRound } from "lucide-react";
import { db } from "@/db";
import { auditLogs, gyms, membershipFreezes, membershipHistory } from "@/db/schema";
import { localDateFor, memberAttendance } from "@/lib/attendance";
import { requireMemberAccess } from "@/lib/auth";
import { can } from "@/lib/permissions";
import { getMember, type MemberStatus } from "@/lib/members";
import { memberFinancials } from "@/lib/payments";
import { MemberStatusBadge } from "@/components/member-status";
import { MemberAvatar } from "@/components/member-avatar";
import { signedMemberPhotoUrl } from "@/lib/member-photos";
import { cancelMembership, resumeMembership } from "@/app/(app)/memberships/actions";
const date = (value: Date | number | null, options?: Intl.DateTimeFormatOptions) => value ? new Intl.DateTimeFormat("en-PK", options ?? { day: "numeric", month: "short", year: "numeric" }).format(value instanceof Date ? value : new Date(value * 1000)) : "—";
const tabs = ["overview", "membership", "attendance", "payments", "notes", "activity"] as const;
export default async function MemberPage({ params, searchParams }: {
    params: Promise<{
        id: string;
    }>;
    searchParams: Promise<{
        tab?: string;
    }>;
}) {
    const { id } = await params;
    const user = await requireMemberAccess(id);
    const { tab: requested } = await searchParams;
    const member = await getMember(user.gymId, id);
    if (!member)
        notFound();
    const financialAccess = can(user.role, "payments.read");
    const tab = tabs.includes(requested as typeof tabs[number]) && !(requested === "payments" && !financialAccess) ? requested! : "overview";
    const gym = (await (db.select({ currency: gyms.currency, timezone: gyms.timezone }).from(gyms)).where(eq(gyms.id, user.gymId)))[0];
    const money = new Intl.NumberFormat("en-PK", { style: "currency", currency: gym?.currency ?? "PKR", maximumFractionDigits: 0 });
    const activity = tab === "activity" ? await (((db.select().from(auditLogs)).where(and(eq(auditLogs.gymId, user.gymId), eq(auditLogs.entityId, id)))).orderBy(desc(auditLogs.createdAt))).limit(20) : [];
    const visits = tab === "attendance" || tab === "overview" ? await memberAttendance(user.gymId, id) : [];
    const financials = financialAccess && (tab === "payments" || tab === "overview") ? await memberFinancials(user.gymId, id) : { invoices: [], payments: [], total: 0, paid: 0, outstanding: 0 };
    const monthPrefix = localDateFor(gym?.timezone ?? "UTC").slice(0, 7), monthVisits = visits.filter(visit => visit.localDate.startsWith(monthPrefix)).length;
    const membershipEvents = tab === "membership" ? await ((db.select().from(membershipHistory)).where(and(eq(membershipHistory.gymId, user.gymId), eq(membershipHistory.memberId, id)))).orderBy(desc(membershipHistory.createdAt)) : [];
    const freezes = member.membershipId ? await ((db.select().from(membershipFreezes)).where(eq(membershipFreezes.membershipId, member.membershipId))).orderBy(desc(membershipFreezes.startDate)) : [];
    const manage = can(user.role, "memberships.write");
    const photoUrl = await signedMemberPhotoUrl(member.profilePhotoUrl, user.gymId);
    return <div className="content"><section className="profile-hero card"><div className="profile-identity"><MemberAvatar firstName={member.firstName} lastName={member.lastName} photoUrl={photoUrl} large/><div><div className="profile-id">{member.memberNumber}</div><h1>{member.firstName} {member.lastName}</h1><div className="profile-meta"><MemberStatusBadge status={member.status as MemberStatus}/><span>{member.membership ?? "No membership"}</span><span>Expires {date(member.membershipEnd)}</span></div></div></div><div className="profile-actions"><Link className="btn btn-secondary" href={`/attendance?member=${id}`}><CalendarCheck size={16}/> Check in</Link>{financialAccess && <Link className="btn btn-secondary" href={"/payments?member=" + id}><CircleDollarSign size={16}/> Record payment</Link>}{manage && <Link className="btn btn-secondary" href={member.membership ? `/members/${id}/membership/renew` : `/members/${id}/membership/new`}><RefreshCw size={16}/> {member.membership ? "Renew" : "Add membership"}</Link>}<Link className="btn btn-primary" href={`/members/${id}/edit`}><Pencil size={16}/> Edit</Link></div></section><nav className="profile-tabs">{tabs.filter(item => item !== "payments" || financialAccess).map(item => <Link key={item} className={tab === item ? "active" : ""} href={`/members/${id}?tab=${item}`}>{item[0].toUpperCase() + item.slice(1)}</Link>)}</nav>
    {tab === "overview" && <div className="profile-grid"><section className="card detail-card"><div className="section-head"><h3>Contact information</h3></div><Detail icon={Phone} label="Phone" value={member.phone}/><Detail icon={Mail} label="Email" value={member.email}/><Detail icon={MapPin} label="Address" value={member.address}/><Detail icon={UserRound} label="Date of birth" value={date(member.dateOfBirth)}/></section><section className="card detail-card"><div className="section-head"><h3>Current membership</h3></div><div className="membership-highlight"><span>{member.membership ?? "No active plan"}</span><strong>{financialAccess && member.membershipPrice ? money.format(member.membershipPrice) : "—"}</strong></div><div className="date-range"><div><small>Started</small><strong>{date(member.membershipStart)}</strong></div><div><small>Expires</small><strong>{date(member.membershipEnd)}</strong></div></div></section><section className="card detail-card"><div className="section-head"><h3>Gym relationship</h3></div><Detail icon={Dumbbell} label="Trainer" value={member.trainerName ?? "Unassigned"}/><Detail icon={Clock3} label="Joined" value={date(member.createdAt)}/><Detail icon={ShieldPlus} label="Emergency contact" value={member.emergencyContactName ? `${member.emergencyContactName}${member.emergencyContactRelationship ? ` · ${member.emergencyContactRelationship}` : ""}` : "Not provided"}/></section><section className="card detail-card"><div className="section-head"><h3>At a glance</h3></div><div className="mini-stat-grid"><div><strong>{monthVisits}</strong><span>Visits this month</span></div>{financialAccess && <div><strong>{money.format(financials.outstanding)}</strong><span>Outstanding</span></div>}</div></section></div>}
    {tab === "membership" && <div className="membership-profile-grid"><section className="card current-membership-card"><div className="section-head"><div><h3>Current membership</h3><span>The member’s latest term and actions</span></div></div>{member.membership ? <><div className="membership-highlight"><span>{member.membership}</span><strong>{financialAccess ? money.format(member.membershipPrice ?? 0) : "—"}</strong></div><div className="date-range"><div><small>Started</small><strong>{date(member.membershipStart)}</strong></div><div><small>Expires</small><strong>{date(member.membershipEnd)}</strong></div></div><div className="membership-summary"><span>Status <MemberStatusBadge status={member.status as MemberStatus}/></span></div>{manage && <div className="membership-buttons"><Link className="btn btn-primary" href={`/members/${id}/membership/renew`}><RefreshCw size={15}/> Renew</Link>{member.status === "frozen" ? <form action={resumeMembership.bind(null, id)}><button className="btn btn-secondary">Resume membership</button></form> : member.status === "active" && <Link className="btn btn-secondary" href={`/members/${id}/membership/freeze`}><Snowflake size={15}/> Freeze</Link>}<form action={cancelMembership.bind(null, id)}><button className="btn btn-danger">Cancel</button></form></div>}</> : <div className="empty-inline"><p>No membership has been assigned.</p>{manage && <Link className="btn btn-primary" href={`/members/${id}/membership/new`}>Create membership</Link>}</div>}</section><section className="card membership-history-card"><div className="section-head"><div><h3>Membership history</h3><span>Renewals, freezes, and status changes</span></div></div>{membershipEvents.length ? <div className="timeline">{membershipEvents.map(event => <div className="timeline-item" key={event.id}><span /><div><strong>{event.action}</strong><small>{date(event.createdAt, { dateStyle: "medium", timeStyle: "short" })}{event.endsAt ? ` · Expires ${date(event.endsAt)}` : ""}</small>{event.notes && <small>{event.notes}</small>}</div></div>)}</div> : <div className="empty-inline">No membership changes recorded yet.</div>}{freezes.length > 0 && <div className="freeze-list"><h4>Freeze periods</h4>{freezes.map(freeze => <div key={freeze.id}><span>{date(freeze.startDate)} → {date(freeze.endDate)}</span><strong>{freeze.days} days · {freeze.status}</strong></div>)}</div>}</section></div>}
    {tab === "attendance" && <section className="card attendance-profile"><div className="section-head"><div><h3>Attendance history</h3><span>{visits.length} recorded visits</span></div><Link className="btn btn-primary" href={`/attendance?member=${id}`}>Check in</Link></div>{visits.length ? <div className="visit-list">{visits.map(visit => <div key={visit.id}><span className="visit-date"><strong>{visit.checkInAt.toLocaleDateString("en-PK", { day: "2-digit" })}</strong><small>{visit.checkInAt.toLocaleDateString("en-PK", { month: "short" })}</small></span><div><strong>{visit.checkInAt.toLocaleTimeString("en-PK", { hour: "numeric", minute: "2-digit" })} check-in</strong><small>{visit.checkOutAt ? `${Math.round((visit.checkOutAt.getTime() - visit.checkInAt.getTime()) / 60000)} minute visit` : "Currently inside"}</small></div><span className={`status-badge ${visit.checkOutAt ? "status-cancelled" : "status-active"}`}>{visit.checkOutAt ? "Completed" : "Inside"}</span></div>)}</div> : <div className="empty-inline">No visits have been recorded for this member.</div>}</section>}{tab === "payments" && <section className="member-financials"><div className="finance-stats"><FinanceMini label="Total invoiced" value={money.format(financials.total)}/><FinanceMini label="Paid" value={money.format(financials.paid)}/><FinanceMini label="Outstanding" value={money.format(financials.outstanding)}/></div><section className="card table-card"><div className="section-head payment-section-head"><div><h3>Invoices</h3><span>Membership charges and payment status</span></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Invoice</th><th>Date</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>{financials.invoices.map(invoice => <tr key={invoice.id}><td><Link className="link mono" href={`/payments/invoices/${invoice.id}`}>{invoice.invoiceNumber}</Link></td><td>{invoice.issuedAt.toLocaleDateString("en-PK")}</td><td>{money.format(invoice.total)}</td><td>{money.format(invoice.paid)}</td><td>{money.format(invoice.balance)}</td><td><span className={`invoice-badge invoice-${invoice.status}`}>{invoice.status.replaceAll("_", " ")}</span></td></tr>)}</tbody></table>{!financials.invoices.length && <div className="empty-inline">No invoices have been created.</div>}</div></section></section>}
    {tab === "notes" && <section className="card tab-panel notes-panel"><div className="panel-icon"><NotebookPen size={20}/></div><h2>Internal notes</h2><p>{member.notes ?? "No internal notes have been added for this member."}</p><Link className="btn btn-secondary" href={`/members/${id}/edit`}>Edit notes</Link></section>}
    {tab === "activity" && <section className="card activity-panel"><div className="section-head"><div><h3>Member activity</h3><span>Important changes to this profile</span></div></div>{activity.length ? <div className="timeline">{activity.map(item => <div className="timeline-item" key={item.id}><span /><div><strong>{item.action.replaceAll(".", " ")}</strong><small>{date(item.createdAt, { dateStyle: "medium", timeStyle: "short" })}</small></div></div>)}</div> : <div className="empty-inline">No activity has been recorded yet.</div>}</section>}</div>;
}
function Detail({ icon: Icon, label, value }: {
    icon: typeof Phone;
    label: string;
    value: string | null;
}) { return <div className="detail-row"><span><Icon size={16}/></span><div><small>{label}</small><strong>{value ?? "Not provided"}</strong></div></div>; }
function FinanceMini({ label, value }: {
    label: string;
    value: string;
}) { return <article className="card finance-mini"><strong>{value}</strong><span>{label}</span></article>; }
