"use client";
import Link from "next/link";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";
import { Bell, CalendarCheck, ChartNoAxesCombined, CreditCard, Dumbbell, LayoutDashboard, LogOut, Menu, ReceiptText, ScrollText, Search, Settings, UserRound, UsersRound, WalletCards, X } from "lucide-react";
import type { RoleKey } from "@/db/schema";
import type { Permission } from "@/lib/permissions";
import { can } from "@/lib/permissions";
import { logout } from "@/app/(app)/actions";
const nav:{label:string;href:string;icon:typeof LayoutDashboard;permission:Permission}[]=[{label:"Dashboard",href:"/dashboard",icon:LayoutDashboard,permission:"dashboard.view"},{label:"Members",href:"/members",icon:UsersRound,permission:"members.read"},{label:"Memberships",href:"/memberships",icon:WalletCards,permission:"memberships.read"},{label:"Attendance",href:"/attendance",icon:CalendarCheck,permission:"attendance.read"},{label:"Payments",href:"/payments",icon:CreditCard,permission:"payments.read"},{label:"Trainers",href:"/trainers",icon:Dumbbell,permission:"trainers.read"},{label:"Expenses",href:"/expenses",icon:ReceiptText,permission:"expenses.read"},{label:"Reports",href:"/reports",icon:ChartNoAxesCombined,permission:"reports.read"}];
export function AppShell({children,user,unreadNotifications=0,gym}:{children:React.ReactNode;user:{name:string;role:RoleKey};unreadNotifications?:number;gym:{name:string;logoUrl:string|null}}){const path=usePathname(),searchRef=useRef<HTMLInputElement>(null),[menuOpen,setMenuOpen]=useState(false);useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();searchRef.current?.focus()}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
const links=<><div className="nav-label">Workspace</div><nav className="nav">{nav.filter(item=>can(user.role,item.permission)).map(({label,href,icon:Icon})=><Link key={href} href={href} className={`nav-item ${path===href?"active":""}`}><Icon size={18}/><span>{label}</span></Link>)}</nav>{can(user.role,"settings.read")&&<><div className="nav-label">Manage</div><nav className="nav"><Link href="/settings" className={`nav-item ${path==="/settings"?"active":""}`}><Settings size={18}/><span>Settings</span></Link>{can(user.role,"users.manage")&&<Link href="/settings/staff" className={`nav-item ${path.startsWith("/settings/staff")?"active":""}`}><UsersRound size={18}/><span>Staff & roles</span></Link>}{can(user.role,"audit.read")&&<Link href="/audit" className={`nav-item ${path==="/audit"?"active":""}`}><ScrollText size={18}/><span>Audit log</span></Link>}</nav></>}</>;
const userCard=<div className="user-card"><div className="avatar">{user.name.slice(0,1)}</div><div className="user-meta"><div className="user-name">{user.name}</div><div className="user-role">{user.role.replace("_"," ")}</div></div><form action={logout}><button className="logout" aria-label="Sign out"><LogOut size={16}/></button></form></div>;
const brand=<Link className="brand" href="/dashboard">{gym.logoUrl?<span className="app-brand-logo"><Image src={gym.logoUrl} alt={`${gym.name} logo`} fill sizes="42px" unoptimized/></span>:<span className="brand-mark">{gym.name.slice(0,1).toUpperCase()}</span>}<span>{gym.name}</span></Link>;
return <div className={`app ${menuOpen?"mobile-menu-open":""}`}><aside className="sidebar">{brand}{links}{userCard}</aside>{menuOpen&&<><button className="mobile-menu-backdrop" aria-label="Close navigation" onClick={()=>setMenuOpen(false)}/><aside className="mobile-sidebar" aria-label="Mobile navigation"><div className="mobile-sidebar-head">{brand}<button className="icon-btn" aria-label="Close navigation" onClick={()=>setMenuOpen(false)}><X size={19}/></button></div><div onClick={()=>setMenuOpen(false)}>{links}</div>{userCard}</aside></>}<main className="main"><header className="topbar"><button className="icon-btn mobile-trigger" aria-label="Open navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(true)}><Menu size={19}/></button><form className="search" action="/members"><Search size={17}/><input ref={searchRef} name="q" className="input" placeholder="Search members by name, phone, email, or ID"/><span className="kbd">⌘ K</span></form><div className="top-actions"><Link className="icon-btn notification-bell" href="/notifications" aria-label={`${unreadNotifications} unread notifications`}><Bell size={18}/>{unreadNotifications>0&&<span>{unreadNotifications>99?"99+":unreadNotifications}</span>}</Link>{can(user.role,"members.write")&&<Link href="/members/new" className="btn btn-primary"><UserRound size={16}/> Add member</Link>}</div></header>{children}</main></div>}
