"use client";
import Link from "next/link";
import { useActionState } from "react";
import { Save } from "lucide-react";
import type { MemberFormState } from "@/app/(app)/members/actions";

type Values={firstName?:string;lastName?:string;profilePhotoUrl?:string|null;dateOfBirth?:Date|null;gender?:string|null;phone?:string|null;email?:string|null;address?:string|null;emergencyContactName?:string|null;emergencyContactRelationship?:string|null;emergencyContactPhone?:string|null;trainerId?:string|null;notes?:string|null;status?:string};
export function MemberForm({action,values={},trainers}:{action:(state:MemberFormState,data:FormData)=>Promise<MemberFormState>;values?:Values;trainers:{id:string;name:string}[]}){
  const [state,formAction,pending]=useActionState(action,{}); const error=(key:string)=>state.fields?.[key]?.[0];
  return <form action={formAction} className="member-form-layout"><div className="form-stack">
    {state.error&&<div className="error" role="alert">{state.error}</div>}
    <section className="card form-card"><h3>Personal information</h3><p>The essentials used to identify and contact this member.</p><div className="form-grid">
      <Field label="First name" name="firstName" value={values.firstName} required error={error("firstName")}/><Field label="Last name" name="lastName" value={values.lastName} required error={error("lastName")}/>
      <Field label="Phone" name="phone" value={values.phone}/><Field label="Email" name="email" type="email" value={values.email} error={error("email")}/>
      <Field label="Date of birth" name="dateOfBirth" type="date" value={values.dateOfBirth instanceof Date?values.dateOfBirth.toISOString().slice(0,10):""}/><div className="field"><label htmlFor="gender">Gender <span className="optional">Optional</span></label><select className="input" id="gender" name="gender" defaultValue={values.gender??""}><option value="">Not specified</option><option value="female">Female</option><option value="male">Male</option><option value="non_binary">Non-binary</option><option value="prefer_not_to_say">Prefer not to say</option></select></div>
      <Field label="Address" name="address" value={values.address} span/><Field label="Profile photo URL" name="profilePhotoUrl" type="url" value={values.profilePhotoUrl} span hint="Optional HTTPS image URL. Protected direct uploads can be connected when storage infrastructure is selected." error={error("profilePhotoUrl")}/>
    </div></section>
    <section className="card form-card"><h3>Emergency contact</h3><p>Optional, but useful when a member needs support.</p><div className="form-grid"><Field label="Contact name" name="emergencyContactName" value={values.emergencyContactName}/><Field label="Relationship" name="emergencyContactRelationship" value={values.emergencyContactRelationship}/><Field label="Phone" name="emergencyContactPhone" value={values.emergencyContactPhone}/></div></section>
    <section className="card form-card"><h3>Internal details</h3><p>Visible only to authorized staff.</p><div className="form-grid"><div className="field"><label htmlFor="trainerId">Assigned trainer <span className="optional">Optional</span></label><select className="input" id="trainerId" name="trainerId" defaultValue={values.trainerId??""}><option value="">Unassigned</option>{trainers.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></div><div className="field"><label htmlFor="status">Account status</label><select className="input" id="status" name="status" defaultValue={values.status??"active"}><option value="active">Active</option><option value="frozen">Frozen</option><option value="cancelled">Cancelled</option></select></div><div className="field span-2"><label htmlFor="notes">Notes <span className="optional">Optional</span></label><textarea className="input textarea" id="notes" name="notes" defaultValue={values.notes??""} rows={4} placeholder="Add context that helps staff serve this member…"/></div></div></section>
  </div><aside className="member-form-aside"><div className="card form-summary"><div className="avatar avatar-lg">{values.firstName?.slice(0,1)||"N"}</div><h3>{values.firstName?`${values.firstName} ${values.lastName??""}`:"New member"}</h3><p>{values.firstName?"Review changes before saving.":"Membership can be assigned after the profile is created."}</p><button className="btn btn-primary btn-block" disabled={pending}><Save size={16}/>{pending?"Saving…":"Save member"}</button><Link className="btn btn-secondary btn-block" href="/members">Cancel</Link></div></aside></form>;
}
function Field({label,name,value,type="text",required,error,span,hint}:{label:string;name:string;value?:string|null;type?:string;required?:boolean;error?:string;span?:boolean;hint?:string}){return <div className={`field ${span?"span-2":""}`}><label htmlFor={name}>{label}{!required&&<span className="optional"> Optional</span>}</label><input className={`input ${error?"input-error":""}`} id={name} name={name} type={type} defaultValue={value??""} required={required}/>{hint&&<small className="field-hint">{hint}</small>}{error&&<small className="field-error">{error}</small>}</div>}
