"use client";
import Link from "next/link";
import Image from "next/image";
import { useActionState, useEffect, useRef, useState } from "react";
import { ImagePlus, Save, Trash2 } from "lucide-react";
import type { MemberFormState } from "@/app/(app)/members/actions";

type Values={firstName?:string;lastName?:string;profilePhotoUrl?:string|null;dateOfBirth?:Date|null;gender?:string|null;phone?:string|null;email?:string|null;address?:string|null;emergencyContactName?:string|null;emergencyContactRelationship?:string|null;emergencyContactPhone?:string|null;trainerId?:string|null;notes?:string|null;status?:string};
export function MemberForm({action,values={},trainers,photoUrl=null}:{action:(state:MemberFormState,data:FormData)=>Promise<MemberFormState>;values?:Values;trainers:{id:string;name:string}[];photoUrl?:string|null}){
  const [state,formAction,pending]=useActionState(action,{}); const error=(key:string)=>state.fields?.[key]?.[0];
  const inputRef=useRef<HTMLInputElement>(null),[preview,setPreview]=useState<string|null>(photoUrl),[removePhoto,setRemovePhoto]=useState(false),[photoError,setPhotoError]=useState<string|null>(null);
  useEffect(()=>()=>{if(preview?.startsWith("blob:"))URL.revokeObjectURL(preview)},[preview]);
  const choosePhoto=(file?:File)=>{setPhotoError(null);if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024){setPhotoError("Photo must be JPG, PNG, or WEBP and smaller than 5 MB.");if(inputRef.current)inputRef.current.value="";return}setPreview(URL.createObjectURL(file));setRemovePhoto(false)};
  const clearPhoto=()=>{setPreview(null);setRemovePhoto(Boolean(values.profilePhotoUrl));setPhotoError(null);if(inputRef.current)inputRef.current.value=""};
  return <form action={formAction} className="member-form-layout"><div className="form-stack">
    {state.error&&<div className="error" role="alert">{state.error}</div>}
    <section className="card form-card"><h3>Personal information</h3><p>The essentials used to identify and contact this member.</p><div className="form-grid">
      <Field label="First name" name="firstName" value={values.firstName} required error={error("firstName")}/><Field label="Last name" name="lastName" value={values.lastName} required error={error("lastName")}/>
      <Field label="Phone" name="phone" value={values.phone}/><Field label="Email" name="email" type="email" value={values.email} error={error("email")}/>
      <Field label="Date of birth" name="dateOfBirth" type="date" value={values.dateOfBirth instanceof Date?values.dateOfBirth.toISOString().slice(0,10):""}/><div className="field"><label htmlFor="gender">Gender <span className="optional">Optional</span></label><select className="input" id="gender" name="gender" defaultValue={values.gender??""}><option value="">Not specified</option><option value="female">Female</option><option value="male">Male</option><option value="non_binary">Non-binary</option><option value="prefer_not_to_say">Prefer not to say</option></select></div>
      <Field label="Address" name="address" value={values.address} span/>
      <div className="field span-2"><label htmlFor="member-photo">Member photo <span className="optional">Optional</span></label><div className="photo-upload"><div className="photo-preview">{preview?<Image src={preview} alt="Selected member photo" fill sizes="112px" unoptimized/>:<span>{(values.firstName?.[0]??"N")}{values.lastName?.[0]??""}</span>}</div><div className="photo-upload-actions"><input ref={inputRef} className="sr-only" id="member-photo" name="photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>choosePhoto(event.target.files?.[0])}/><input type="hidden" name="removePhoto" value={removePhoto?"true":"false"}/><button className="btn btn-secondary" type="button" onClick={()=>inputRef.current?.click()}><ImagePlus size={16}/>{preview?"Change photo":"Upload photo"}</button>{(preview||Boolean(values.profilePhotoUrl&&!removePhoto))&&<button className="btn btn-secondary" type="button" onClick={clearPhoto}><Trash2 size={16}/>Remove</button>}<small>JPG, PNG or WEBP. Maximum 5 MB.</small></div></div>{photoError&&<small className="field-error" role="alert">{photoError}</small>}</div>
    </div></section>
    <section className="card form-card membership-default"><h3>Membership</h3><p>Every new member starts on the gym&apos;s Standard plan. Owners can manage advanced plans separately.</p><div><strong>Standard</strong><span>Assigned automatically when this profile is created.</span></div></section>
    <section className="card form-card"><h3>Emergency contact</h3><p>Optional, but useful when a member needs support.</p><div className="form-grid"><Field label="Contact name" name="emergencyContactName" value={values.emergencyContactName}/><Field label="Relationship" name="emergencyContactRelationship" value={values.emergencyContactRelationship}/><Field label="Phone" name="emergencyContactPhone" value={values.emergencyContactPhone}/></div></section>
    <section className="card form-card"><h3>Internal details</h3><p>Visible only to authorized staff.</p><div className="form-grid"><div className="field"><label htmlFor="trainerId">Assigned trainer <span className="optional">Optional</span></label><select className="input" id="trainerId" name="trainerId" defaultValue={values.trainerId??""}><option value="">Unassigned</option>{trainers.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></div><div className="field"><label htmlFor="status">Account status</label><select className="input" id="status" name="status" defaultValue={values.status??"active"}><option value="active">Active</option><option value="frozen">Frozen</option><option value="cancelled">Cancelled</option></select></div><div className="field span-2"><label htmlFor="notes">Notes <span className="optional">Optional</span></label><textarea className="input textarea" id="notes" name="notes" defaultValue={values.notes??""} rows={4} placeholder="Add context that helps staff serve this member…"/></div></div></section>
  </div><aside className="member-form-aside"><div className="card form-summary">{preview?<div className="summary-photo"><Image src={preview} alt="Member preview" fill sizes="58px" unoptimized/></div>:<div className="avatar avatar-lg">{values.firstName?.slice(0,1)||"N"}</div>}<h3>{values.firstName?`${values.firstName} ${values.lastName??""}`:"New member"}</h3><p>{values.firstName?"Review changes before saving.":"Standard membership will be assigned automatically."}</p><button className="btn btn-primary btn-block" disabled={pending||Boolean(photoError)}><Save size={16}/>{pending?"Saving…":"Save member"}</button><Link className="btn btn-secondary btn-block" href="/members">Cancel</Link></div></aside></form>;
}
function Field({label,name,value,type="text",required,error,span,hint}:{label:string;name:string;value?:string|null;type?:string;required?:boolean;error?:string;span?:boolean;hint?:string}){return <div className={`field ${span?"span-2":""}`}><label htmlFor={name}>{label}{!required&&<span className="optional"> Optional</span>}</label><input className={`input ${error?"input-error":""}`} id={name} name={name} type={type} defaultValue={value??""} required={required}/>{hint&&<small className="field-hint">{hint}</small>}{error&&<small className="field-error">{error}</small>}</div>}
