import {copyFileSync,mkdirSync,rmSync} from "node:fs";import {hashSync} from "bcryptjs";import Database from "better-sqlite3";import postgres from "postgres";
mkdirSync(".tmp",{recursive:true});for(const suffix of ["","-wal","-shm"])rmSync(`.tmp/form-e2e.db${suffix}`,{force:true});copyFileSync("data/gym.db",".tmp/form-e2e.db");
const db=new Database(".tmp/form-e2e.db");db.pragma("foreign_keys = ON");const tables=["notification_reads","password_tokens","sessions","role_permissions","notifications","audit_logs","attendance","payments","invoice_items","invoices","membership_freezes","membership_history","memberships","members","membership_plans","expenses","expense_categories","trainers","users","settings","roles","gyms"];
db.transaction(()=>{for(const table of tables)db.prepare(`DELETE FROM ${table}`).run();})();
const passwordHash=hashSync("BrowserQA2026!",12),now=Math.floor(Date.now()/1000),future=now+90*86400;
const permissions=["dashboard.view","members.read","members.write","members.archive","memberships.read","memberships.write","attendance.read","attendance.write","attendance.override","payments.read","payments.write","trainers.read","trainers.write","expenses.read","expenses.write","reports.read","settings.read","settings.write","users.manage","audit.read"];
const roleMap:{[key:string]:string[]}={owner:permissions,manager:permissions.filter(p=>p!=="audit.read"),receptionist:["dashboard.view","members.read","members.write","memberships.read","memberships.write","attendance.read","attendance.write","payments.read","payments.write","trainers.read"],trainer:["dashboard.view","members.read","attendance.read","trainers.read"]};
db.transaction(()=>{for(const key of permissions)db.prepare("INSERT OR IGNORE INTO permissions(id,key,description) VALUES(?,?,?)").run(`permission_${key}`,key,key.replace("."," "));for(const gym of ["a","b"]){const gid=`e2e_gym_${gym}`;db.prepare("INSERT INTO gyms(id,name,slug,country,timezone,currency,locale,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").run(gid,`E2E Gym ${gym.toUpperCase()}`,`e2e-gym-${gym}`,gym==="a"?"PK":"GB",gym==="a"?"Asia/Karachi":"Europe/London",gym==="a"?"PKR":"GBP",gym==="a"?"en-PK":"en-GB",now,now);for(const role of Object.keys(roleMap)){const rid=`e2e_${gym}_${role}`;db.prepare("INSERT INTO roles(id,gym_id,key,name,created_at,updated_at) VALUES(?,?,?,?,?,?)").run(rid,gid,role,role[0].toUpperCase()+role.slice(1),now,now);for(const permission of roleMap[role])db.prepare("INSERT INTO role_permissions(role_id,permission_id) VALUES(?,?)").run(rid,`permission_${permission}`)}for(const [category,key,value] of [["membership","expiry_warning_days","[30,7,1]"],["membership","freeze_rules",'{"extendExpiry":true,"maxDays":30}'],["payment","methods",'["Cash","Card","Bank Transfer","Online","Other"]'],["notification","channels",'{"inApp":true,"email":false,"sms":false,"whatsapp":false}']])db.prepare("INSERT INTO settings(id,gym_id,category,key,value,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").run(`e2e_${gym}_${key}`,gid,category,key,value,now,now);const accounts:gymAccount[] = gym==="a"?[{role:"owner",name:"Olivia Owner",email:"owner.a@e2e.test"},{role:"manager",name:"Manny Manager",email:"manager.a@e2e.test"},{role:"receptionist",name:"Riley Reception",email:"reception.a@e2e.test"},{role:"trainer",name:"Tara Trainer",email:"trainer.a@e2e.test"}]:[{role:"owner",name:"Ben Owner",email:"owner.b@e2e.test"}];for(const account of accounts)db.prepare("INSERT INTO users(id,gym_id,role_id,name,email,password_hash,active,must_change_password,created_at,updated_at) VALUES(?,?,?,?,?,?,1,0,?,?)").run(`e2e_${gym}_user_${account.role}`,gid,`e2e_${gym}_${account.role}`,account.name,account.email,passwordHash,now,now)}
db.prepare("INSERT INTO trainers(id,gym_id,user_id,name,email,status,created_at,updated_at) VALUES(?,?,?,?,?,'active',?,?)").run("e2e_a_trainer","e2e_gym_a","e2e_a_user_trainer","Tara Trainer","trainer.a@e2e.test",now,now);db.prepare("INSERT INTO trainers(id,gym_id,name,email,status,created_at,updated_at) VALUES(?,?,?,?, 'active',?,?)").run("e2e_a_other_trainer","e2e_gym_a","Other Coach","other.coach@e2e.test",now,now);db.prepare("INSERT INTO trainers(id,gym_id,name,email,status,created_at,updated_at) VALUES(?,?,?,?, 'active',?,?)").run("e2e_b_trainer","e2e_gym_b","Gym B Coach","coach.b@e2e.test",now,now);
for(const row of [["e2e_a_member","e2e_gym_a","A-1001","Alice","Assigned","e2e_a_trainer"],["e2e_a_unrelated","e2e_gym_a","A-1002","Uma","Unrelated","e2e_a_other_trainer"],["e2e_b_member","e2e_gym_b","B-1001","Bea","Boundary","e2e_b_trainer"]])db.prepare("INSERT INTO members(id,gym_id,member_number,first_name,last_name,email,trainer_id,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(row[0],row[1],row[2],row[3],row[4],`${String(row[3]).toLowerCase()}@e2e.test`,row[5],"active",now,now);
for(const gym of ["a","b"]){db.prepare("INSERT INTO membership_plans(id,gym_id,name,duration_days,price,active,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?)").run(`e2e_${gym}_plan`,`e2e_gym_${gym}`,"Monthly QA",30,gym==="a"?10000:100,now,now);db.prepare("INSERT INTO memberships(id,gym_id,member_id,plan_id,status,starts_at,ends_at,base_price,final_price,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(`e2e_${gym}_membership`,`e2e_gym_${gym}`,`e2e_${gym}_member`,`e2e_${gym}_plan`,"active",now-86400,future,gym==="a"?10000:100,gym==="a"?10000:100,now,now);db.prepare("INSERT INTO invoices(id,gym_id,member_id,membership_id,invoice_number,issued_at,due_at,subtotal,discount,tax,total,paid,balance,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(`e2e_${gym}_invoice`,`e2e_gym_${gym}`,`e2e_${gym}_member`,`e2e_${gym}_membership`,`E2E-${gym.toUpperCase()}-001`,now,now,gym==="a"?10000:100,0,0,gym==="a"?10000:100,0,gym==="a"?10000:100,"unpaid",now,now);db.prepare("INSERT INTO invoice_items(id,invoice_id,description,quantity,unit_price,amount,created_at) VALUES(?,?,?,?,?,?,?)").run(`e2e_${gym}_item`,`e2e_${gym}_invoice`,"Monthly QA membership",1,gym==="a"?10000:100,gym==="a"?10000:100,now)}
db.prepare("INSERT INTO attendance(id,gym_id,member_id,membership_id,local_date,check_in_at,check_out_at,method,override_used,staff_user_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run("e2e_a_attendance_unrelated","e2e_gym_a","e2e_a_unrelated",null,"2026-08-18",now-3600,now-1800,"manual_search",0,"e2e_a_user_owner",now);
})();db.close();

async function syncToPostgres(){
process.loadEnvFile?.(".env");const url=process.env.DATABASE_URL;if(!url?.startsWith("postgres"))throw new Error("E2E requires a PostgreSQL DATABASE_URL.");
const source=new Database(".tmp/form-e2e.db",{readonly:true});const target=postgres(url,{prepare:false,max:1,ssl:"require",connect_timeout:15});
const tables=["permissions","gyms","roles","role_permissions","users","settings","trainers","members","membership_plans","memberships","invoices","invoice_items","attendance"];
const timestamps=new Set(["created_at","updated_at","expires_at","used_at","last_login_at","occurred_at","read_at","joining_date","date_of_birth","archived_at","starts_at","ends_at","cancelled_at","start_date","end_date","resumed_at","issued_at","due_at","paid_at","check_in_at","check_out_at","expense_date"]);
const booleans=new Set(["active","must_change_password","override_used"]);const json=new Set(["value","metadata"]);
try{await target.begin(async sql=>{
await sql`delete from notification_reads where user_id like 'e2e_%' or notification_id in (select id from notifications where gym_id like 'e2e_gym_%')`;
await sql`delete from password_tokens where user_id like 'e2e_%'`;await sql`delete from sessions where user_id like 'e2e_%'`;
await sql`delete from invoice_items where invoice_id in (select id from invoices where gym_id like 'e2e_gym_%')`;await sql`delete from membership_freezes where gym_id like 'e2e_gym_%'`;await sql`delete from membership_history where gym_id like 'e2e_gym_%'`;await sql`delete from attendance where gym_id like 'e2e_gym_%'`;await sql`delete from payments where gym_id like 'e2e_gym_%'`;await sql`delete from invoices where gym_id like 'e2e_gym_%'`;await sql`delete from memberships where gym_id like 'e2e_gym_%'`;await sql`delete from members where gym_id like 'e2e_gym_%'`;await sql`delete from membership_plans where gym_id like 'e2e_gym_%'`;await sql`delete from expenses where gym_id like 'e2e_gym_%'`;await sql`delete from expense_categories where gym_id like 'e2e_gym_%'`;await sql`delete from notifications where gym_id like 'e2e_gym_%'`;await sql`delete from audit_logs where gym_id like 'e2e_gym_%'`;await sql`delete from trainers where gym_id like 'e2e_gym_%'`;await sql`delete from settings where gym_id like 'e2e_gym_%'`;await sql`delete from role_permissions where role_id like 'e2e_%'`;await sql`delete from users where gym_id like 'e2e_gym_%'`;await sql`delete from roles where gym_id like 'e2e_gym_%'`;await sql`delete from gyms where id like 'e2e_gym_%'`;await sql`delete from auth.users where email like '%@e2e.test'`;
for(const table of tables){const rows=(source.prepare(`select * from "${table}"`).all() as Record<string,unknown>[]).map(row=>Object.fromEntries(Object.entries(row).map(([column,value])=>{if(value==null)return[column,null];if(timestamps.has(column)&&typeof value==="number")return[column,new Date(value*1000)];if(booleans.has(column))return[column,Boolean(value)];if(json.has(column)&&typeof value==="string")return[column,JSON.parse(value)];return[column,value]})));if(rows.length)await sql`insert into ${sql(table)} ${sql(rows,...Object.keys(rows[0]))} on conflict do nothing`;}
await sql`insert into auth.users (instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,confirmation_token,recovery_token,email_change_token_new,email_change,raw_app_meta_data,raw_user_meta_data,is_super_admin,created_at,updated_at,phone,phone_change,phone_change_token,email_change_token_current,email_change_confirm_status,reauthentication_token,is_sso_user,is_anonymous) select '00000000-0000-0000-0000-000000000000'::uuid,gen_random_uuid(),'authenticated','authenticated',lower(u.email),u.password_hash,now(),'','','','',jsonb_build_object('provider','email','providers',jsonb_build_array('email')),jsonb_build_object('name',u.name),false,u.created_at,now(),null,'','','',0,'',false,false from public.users u where u.gym_id like 'e2e_gym_%' and not exists(select 1 from auth.users au where lower(au.email)=lower(u.email))`;
await sql`insert into auth.identities(provider_id,user_id,identity_data,provider,last_sign_in_at,created_at,updated_at) select au.id::text,au.id,jsonb_build_object('sub',au.id::text,'email',au.email,'email_verified',true,'phone_verified',false),'email',null,au.created_at,now() from auth.users au join public.users u on lower(u.email)=lower(au.email) where u.gym_id like 'e2e_gym_%' and not exists(select 1 from auth.identities ai where ai.user_id=au.id and ai.provider='email')`;
});console.log("Isolated PostgreSQL Playwright data prepared.");}finally{source.close();await target.end();}}
syncToPostgres().catch(error=>{console.error(error instanceof Error?error.message:error);process.exitCode=1});
type gymAccount={role:"owner"|"manager"|"receptionist"|"trainer";name:string;email:string};
