"use client";
import Link from "next/link";
import { useActionState } from "react";
import { ArrowRight } from "lucide-react";
import { register } from "./actions";
export function RegisterForm(){const [state,action,pending]=useActionState(register,{});const error=(key:string)=>state.fields?.[key]?.[0];return <form action={action} className="form-stack">
  {state.error&&<div className="error" role="alert">{state.error}</div>}
  <div><div className="eyebrow">Your account</div><div className="form-grid"><Field name="firstName" label="First name" error={error("firstName")}/><Field name="lastName" label="Last name" error={error("lastName")}/><Field name="email" label="Email address" type="email" error={error("email")} span/><Field name="password" label="Password" type="password" error={error("password")}/><Field name="confirmPassword" label="Confirm password" type="password" error={error("confirmPassword")}/></div></div>
  <div><div className="eyebrow">Your gym</div><div className="form-grid"><Field name="gymName" label="Gym name" error={error("gymName")} span/><Select name="country" label="Country" options={[["US","United States"],["GB","United Kingdom"],["AE","United Arab Emirates"],["SA","Saudi Arabia"],["DE","Germany"],["PK","Pakistan"],["CA","Canada"],["AU","Australia"],["SG","Singapore"],["MY","Malaysia"]]}/><Select name="currency" label="Currency" options={[["USD","USD — US Dollar"],["GBP","GBP — British Pound"],["EUR","EUR — Euro"],["AED","AED — UAE Dirham"],["SAR","SAR — Saudi Riyal"],["PKR","PKR — Pakistani Rupee"],["CAD","CAD — Canadian Dollar"],["AUD","AUD — Australian Dollar"],["SGD","SGD — Singapore Dollar"],["MYR","MYR — Malaysian Ringgit"]]}/><Select name="timezone" label="Timezone" span options={[["UTC","UTC"],["America/New_York","America/New_York"],["America/Los_Angeles","America/Los_Angeles"],["Europe/London","Europe/London"],["Europe/Berlin","Europe/Berlin"],["Asia/Dubai","Asia/Dubai"],["Asia/Riyadh","Asia/Riyadh"],["Asia/Karachi","Asia/Karachi"],["Asia/Singapore","Asia/Singapore"],["Asia/Kuala_Lumpur","Asia/Kuala_Lumpur"],["Australia/Sydney","Australia/Sydney"]]}/></div></div>
  <button className="btn btn-primary btn-block" disabled={pending}>{pending?"Creating your gym…":<>Create gym <ArrowRight size={16}/></>}</button><p className="demo-note">Already have an account? <Link className="link" href="/login">Sign in</Link></p>
 </form>}
function Field({name,label,type="text",error,span}:{name:string;label:string;type?:string;error?:string;span?:boolean}){return <div className={`field ${span?"span-2":""}`}><label htmlFor={name}>{label}</label><input className={`input ${error?"input-error":""}`} id={name} name={name} type={type} required autoComplete={name==="email"?"email":name.includes("password")||name.includes("Password")?"new-password":undefined}/>{error&&<small className="field-error">{error}</small>}</div>}
function Select({name,label,options,span}:{name:string;label:string;options:string[][];span?:boolean}){return <div className={`field ${span?"span-2":""}`}><label htmlFor={name}>{label}</label><select className="input" id={name} name={name}>{options.map(([value,text])=><option value={value} key={value}>{text}</option>)}</select></div>}
